# Generated by Django 4.2 on 2023-05-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Labels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("label", models.ManyToManyField(to="tasks.tasks")),
            ],
        ),
    ]
