# Generated by Django 4.2.1 on 2023-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labels",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="Name"),
        ),
    ]
