# Generated by Django 4.2 on 2023-05-23 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0002_alter_labels_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labels",
            old_name="label",
            new_name="tasks",
        ),
    ]
