# Generated by Django 4.2 on 2023-05-23 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0003_rename_label_labels_tasks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="labels",
            options={},
        ),
        migrations.RemoveField(
            model_name="labels",
            name="tasks",
        ),
    ]
