# Generated by Django 4.2 on 2023-05-23 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={"ordering": ["task"]},
        ),
    ]
