# Generated by Django 4.2.1 on 2023-06-05 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("labels", "0001_initial"),
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="executor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="executor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Executor",
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                through="tasks.LabelForTask",
                to="labels.labels",
                verbose_name="Labels",
            ),
        ),
        migrations.AddField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="statuses.statuses",
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="labelfortask",
            name="labels",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="labels.labels"
            ),
        ),
        migrations.AddField(
            model_name="labelfortask",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.tasks"
            ),
        ),
    ]
