# Generated by Django 4.2 on 2023-05-23 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0004_alter_labels_options_remove_labels_tasks"),
        ("tasks", "0002_alter_tasks_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LabelForTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="labels.labels"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.tasks"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tasks",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                through="tasks.LabelForTask",
                to="labels.labels",
                verbose_name="Labels",
            ),
        ),
    ]
