# Generated by Django 4.2.1 on 2023-05-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0002_alter_labels_name"),
        ("tasks", "0003_alter_tasks_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="labels",
        ),
        migrations.AddField(
            model_name="tasks",
            name="label",
            field=models.ManyToManyField(
                blank=True,
                through="tasks.LabelForTask",
                to="labels.labels",
                verbose_name="Label",
            ),
        ),
    ]
