# Generated by Django 4.2 on 2023-05-23 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_labelfortask_tasks_labels"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={},
        ),
    ]
