# Generated by Django 4.2 on 2023-05-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_tasks_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="description",
            field=models.TextField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="task_name",
            field=models.CharField(max_length=255, verbose_name="Name"),
        ),
    ]
