# Generated by Django 4.2.1 on 2023-05-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labels", "0002_alter_labels_name"),
        ("tasks", "0004_remove_tasks_labels_tasks_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="labelfortask",
            old_name="label",
            new_name="labels",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="label",
        ),
        migrations.AddField(
            model_name="tasks",
            name="labels",
            field=models.ManyToManyField(
                blank=True,
                through="tasks.LabelForTask",
                to="labels.labels",
                verbose_name="Labels",
            ),
        ),
    ]
