# Generated by Django 4.2 on 2023-05-17 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("statuses", "0001_initial"),
        ("tasks", "0005_alter_tasks_description_alter_tasks_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="performer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="performed_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Performer",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="statuses.statuses",
                verbose_name="Status",
            ),
        ),
    ]
