# Generated by Django 4.2 on 2023-05-19 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("statuses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="statuses",
            old_name="created",
            new_name="created_at",
        ),
    ]
